package org.davilj.trademe.bucket;/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'daniev' at '4/13/17 8:28 PM' with Gradle 3.2.1
 *
 * @author daniev, @date 4/13/17 8:28 PM
 */
// Imports the Google Cloud client library

import com.google.auth.oauth2.ServiceAccountCredentials;
import com.google.cloud.storage.*;
import org.davilj.trademe.bucket.impl.GoogleBucket;

import java.io.*;


public class BucketFactory {

    public static IBucket getGoogleBucket(String bucketName) throws Exception {
        // Instantiates a client
        Storage storage = StorageOptions.newBuilder()
                .setProjectId("tradememining")
                .setCredentials(ServiceAccountCredentials.fromStream(new FileInputStream("trademeMining-key.json")))
                .build()
                .getService();

        return new GoogleBucket(storage, bucketName);
    }
}

