/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'daniev' at '4/13/17 8:28 PM' with Gradle 3.2.1
 *
 * @author daniev, @date 4/13/17 8:28 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
